[project]
name = "gittop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "distro>=1.9.0",
    "pandas>=2.2.3",
    "psutil>=6.1.1",
    "rich>=13.9.4",
    "screeninfo>=0.8.1",
]
